class ManagerStrings {
  static const String appName = 'اذكار';
  static const String aboutScreen = 'About Screen';
  static const String notFoundRoute = 'Route Not Found';
  static const String signUp = 'Sign Up';
  static const String login = 'Log In';
  static const String emailOrPhone = 'Email or Phone';
  static const String start = 'Start';
  static const String name = 'Name';
  static const String confirmPassword = 'Confirm Password';
  static const String outBoarding1 = 'Start Shopping ';
  static const String outBoarding2 = 'EveryThing You need ... Shop And Enjoy ';
  static const String labelText = 'Enter Email or Phone';
  static const String labelText2 = 'Enter Password';
  static const String enterEmail = 'Enter Email';
  static const String enterName = 'Enter Name';
  static const String enterPhone = 'Enter Phone';
  static const String password = 'Password';
  static const String email = 'Email';
  static const String phoneNumber = 'Phone Number';
  static const String forgotPassword = 'Forgot Password ?';
  static const String doNotHaveAnAccount = 'Do Not Have an Account ?';
  static const String haveAnAccount = 'Have an Account ?';
  static const String remember = 'Remember';
  static const String agreeOn = 'Agree on ';
  static const String terms = 'Terms ';
  static const String and = 'And ';
  static const String conditions = 'Conditions ';
  static const String men = 'Men ';
  static const String women = 'Women ';
  static const String clothes = 'Clothes ';
  static const String bags = 'Bags ';
  static const String shoes = 'Shoes ';
  static const String accessory = 'Accessory ';
  static const String brand = 'Brand ';
  static const String dress = 'Dresses ';
  static const String seasonNew = 'Season New ';
  static const String home = 'Home';
  static const String cart = 'Cart';
  static const String profile = 'Profile';
  static const String settings = 'Settings';
  static const String shopFromBestSeller = 'Shop From the Best Seller';
  static const String viewAll = 'View All';
  static const String shopForTheFirstTime = 'Shop For the First Time';
  static const String andGet = 'and Get 50%';
  static const String hello = 'Hello,';


}